version: '3.5'

services:
    db:
        build:
            dockerfile: Dockerfile.dev
            context: ./api/database/
        container_name: blackblade-db
        command: --sql_mode=""
        volumes:
            - ./api/database:/database
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=blackblade
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./api
        container_name: blackblade-api
        depends_on:
            - 'db'
        volumes:
            - ./api:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - '8000:8000'
        environment:
            - API_PORT=${API_PORT:?err}
            - DB_HOST=${DB_HOST:?err}
            - DB_USERNAME=${DB_USERNAME:?err}
            - DB_PASSWORD=${DB_PASSWORD:?err}
            - DB_DATABASE=${DB_DATABASE:?err}
            - EMAIL_ENC_KEY=${EMAIL_ENC_KEY:?err}
            - MAILJET_PUBLIC_KEY=${MAILJET_PUBLIC_KEY:?err}
            - MAILJET_PRIVATE_KEY=${MAILJET_PRIVATE_KEY:?err}
            - BLACKBLADE_DOMAIN=${BLACKBLADE_DOMAIN:?err}
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        container_name: blackblade-nginx
        ports:
            - '8100:80'
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        container_name: blackblade-client
        volumes:
            - /app/node_modules
            - ./client:/app
        environment:
            - CI=true

networks:
    default:
        name: blackblade_core
