version: '3.5'

services:
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./api
        container_name: blackblade-api
        volumes:
            - ./api:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - '8000:8000'
        environment:
            - ENVIRONMENT=${ENVIRONMENT:?err}
            - API_PORT=${API_PORT:?err}
            - DB_HOST=${DB_HOST:?err}
            - DB_USERNAME=${DB_USERNAME:?err}
            - DB_PASSWORD=${DB_PASSWORD:?err}
            - DB_DATABASE=${DB_DATABASE:?err}
            - DB_PORT=${DB_PORT:?err}
            - MAILJET_PUBLIC_KEY=${MAILJET_PUBLIC_KEY:?err}
            - MAILJET_PRIVATE_KEY=${MAILJET_PRIVATE_KEY:?err}
            - BLACKBLADE_DOMAIN=${BLACKBLADE_DOMAIN:?err}
            - SESSION_SECRET=${SESSION_SECRET:?err}
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        container_name: blackblade-nginx
        ports:
            - '8100:80'
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        container_name: blackblade-client
        volumes:
            - /app/node_modules
            - ./client:/app
        environment:
            - CI=true
networks:
    default:
        external:
            name: blackblade_core
