version: 2.1

jobs:
    build_and_deploy:
        docker:
            - image: google/cloud-sdk
        steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: 'Build & push images to Dockerhub'
                  command: |
                      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                      docker build -t brandonwade/blackblade-db:latest -t brandonwade/blackblade-db:$CIRCLE_SHA1 -f ./api/database/Dockerfile ./api/database
                      docker build -t brandonwade/blackblade-api:latest -t brandonwade/blackblade-api:$CIRCLE_SHA1 -f ./api/Dockerfile ./api
                      docker build -t brandonwade/blackblade-client:latest -t brandonwade/blackblade-client:$CIRCLE_SHA1 -f ./client/Dockerfile ./client
                      docker push brandonwade/blackblade-db:latest
                      docker push brandonwade/blackblade-db:$CIRCLE_SHA1
                      docker push brandonwade/blackblade-api:latest
                      docker push brandonwade/blackblade-api:$CIRCLE_SHA1
                      docker push brandonwade/blackblade-client:latest
                      docker push brandonwade/blackblade-client:$CIRCLE_SHA1
            - run:
                  name: 'Authenticate with GCP'
                  command: |
                      openssl aes-256-cbc -d -in service-account.json.enc -out service-account.json -k $SERVICE_ACCOUNT_ENCRYPTION_KEY
                      gcloud auth activate-service-account --key-file=service-account.json
                      gcloud --quiet config set project ${GCP_PROJECT_ID}
                      gcloud --quiet config set compute/zone ${GCP_COMPUTE_ZONE}
                      gcloud container clusters get-credentials ${GCP_CLUSTER_NAME}
            - run:
                  name: 'Update Kubernetes with the latest configs'
                  command: |
                      kubectl apply -f k8s
            - run:
                  name: 'Update pods with the latest image versions'
                  command: |
                      kubectl set image deployments/db-deployment blackblade-db=brandonwade/blackblade-db:$CIRCLE_SHA1
                      kubectl set image deployments/api-deployment blackblade-api=brandonwade/blackblade-api:$CIRCLE_SHA1
                      kubectl set image deployments/client-deployment blackblade-client=brandonwade/blackblade-client:$CIRCLE_SHA1
workflows:
    version: 2.1
    build_and_deploy:
        jobs:
            - build_and_deploy:
                  filters:
                      branches:
                          only:
                              - master
