export const SET_DECK_NAME = 'SET_DECK_NAME';
export const SET_DECK_CARDS = 'SET_DECK_CARDS';
export const SET_MAYBEBOARD_CARDS = 'SET_MAYBEBOARD_CARDS';
export const SET_UNMODIFIED_DECK_NAME = 'SET_UNMODIFIED_DECK_NAME';
export const SET_UNMODIFIED_DECK_CARDS = 'SET_UNMODIFIED_DECK_CARDS';
export const SET_UNMODIFIED_MAYBEBOARD_CARDS = 'SET_UNMODIFIED_MAYBEBOARD_CARDS';
export const SET_MAYBEBOARD_MODE = 'SET_MAYBEBOARD_MODE';
