apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: api
    template:
        metadata:
            labels:
                component: api
        spec:
            containers:
                - name: blackblade-api
                  image: brandonwade/blackblade-api:latest
                  ports:
                      - containerPort: 8000
                  env:
                      - name: ENVIRONMENT
                        valueFrom:
                            secretKeyRef:
                                name: environment
                                key: ENVIRONMENT
                      - name: API_PORT
                        valueFrom:
                            secretKeyRef:
                                name: apiport
                                key: API_PORT
                      - name: DB_HOST
                        valueFrom:
                            secretKeyRef:
                                name: dbhost
                                key: DB_HOST
                      - name: DB_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: mysqluser
                                key: MYSQL_USER
                      - name: DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysqlpassword
                                key: MYSQL_PASSWORD
                      - name: DB_DATABASE
                        value: blackblade
                      - name: DB_PORT
                        valueFrom:
                            secretKeyRef:
                                name: dbport
                                key: DB_PORT
                      - name: MAILJET_PUBLIC_KEY
                        valueFrom:
                            secretKeyRef:
                                name: mailjetpublickey
                                key: MAILJET_PUBLIC_KEY
                      - name: MAILJET_PRIVATE_KEY
                        valueFrom:
                            secretKeyRef:
                                name: mailjetprivatekey
                                key: MAILJET_PRIVATE_KEY
                      - name: BLACKBLADE_DOMAIN
                        valueFrom:
                            secretKeyRef:
                                name: blackbladedomain
                                key: BLACKBLADE_DOMAIN
                      - name: SESSION_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: sessionsecret
                                key: SESSION_SECRET
