apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: blackblade-ca-tls
spec:
    secretName: blackblade-ca
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: bwade.dev
    dnsNames:
        - bwade.dev
