apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: blackblade-ca-tls
spec:
    secretName: blackblade-ca
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: blackblade.ca
    dnsNames:
        - blackblade.ca
    acme:
        config:
            - http01:
                  ingressClass: nginx
              domains:
                  - blackblade.ca
